### ISSUE TITLE
[Bug]: Trying to configure an NFS share for the downloads volume fails with " Forbidden: may not specify more than 1 volume type"

### ISSUE THREAD

**Issue by Varashi** [drinkataco/media-servarr#28]
### Chart Name and Version

sabnzbd 0.1.1

### Helm Version

Version:"v3.12.3

### Kubernetes Version

v1.30

### Bug Description

I try to follow the instructions in the sabnzbd helm chart readme to mount an NFS export into the downloads volume.
When deploying the helm chart I get the following error:

Helm install failed for release sabnzbd/sabnzbd with chart sabnzbd@0.1.0: 1 error occurred: * Deployment.apps "sabnzbd" is invalid: [spec.template.spec.volumes[1].nfs: Forbidden: may not specify more than 1 volume type, spec.template.spec.containers[0].volumeMounts[1].name: Not found: "downloads"]

### Steps to Reproduce

Deploy the chart with the following values .yaml in it:

...
   deployment:
      container:
        image:
          repository: 'lscr.io/linuxserver/sabnzbd'
        env:
          - name: 'PGID'
            value: '1000'
          - name: 'PUID'
            value: '1000'
        volumeMounts:
          - name: 'config'
            mountPath: '/config'
          - name: 'downloads'
            mountPath: '/config/Downloads'
      volumes:
        config:
          persistentVolumeClaim:
            claimName: 'sabnzbd-config'
        downloads:
          nfs:
            server: 'skw-truenas-data'
            path: '/mnt/DATA/Media'
    persistentVolumeClaims:
      sabnzbd-config:
        accessMode: 'ReadWriteOnce'
        requestStorage: '1Gi'
        selector: {}
    ingress:
...

### Expected Behavior

The helm deployment would succeed, and within the pod /config/Downloads would point to the  /mnt/DATA/Media folder on my truenas appliance.

**Comment by drinkataco** [comment]
@Varashi Sorry for the late reply;

This is probably an issue because by default an `emptyDir` is set. I will action a fix for this.

In the mean time, a workaround should be defining the nfs drive in values.yaml like this:

```
deployment:
  volumes:
    ...
    downloads:
      nfs:
        server: 'skw-truenas-data'
        path: '/mnt/DATA/Media'
      emptyDir:
```

The `emptyDir` being set empty should nullify the previous defined value (`emptyDir: {}`) which is set in the default [values.yaml](https://github.com/drinkataco/media-servarr/blob/main/charts/sabnzbd/values.yaml#L78-L79).

A longer term solution would be to make sure these values are not merged in the future (which is causing two drives to be defined). I'll action this on the weekend!

**Comment by Varashi** [comment]
Awesome. Many thanks for the feedback.
In the meantime I've utilised a different helm chart to get the *arr stack up and running, but I'll try to verify your workaround in the weekend.

**Comment by drinkataco** [comment]
Fixed with https://github.com/drinkataco/media-servarr/pull/30
